### ISSUE TITLE
Sent emails aren't displayed in webapp sent folder

### ISSUE THREAD

**Issue by c-w** [ascoderu/lokole#319]
From @nzola:

> Emails sent by Lokole user from the Lokole BOX is displayed in the Lokole BOX “sent-box”, but not mirrored in the Lokole WEB “sent-box”.
> Emails sent by Lokole user from the Lokole WEB is displayed in the Lokole WEB “sent-box”, but not mirrored in the Lokole BOX “sent-box”.

Perhaps something in the wiring of the [IndexSentEmailForMailbox](https://github.com/ascoderu/opwen-cloudserver/blob/63236a82cbe6318cb8c7090b2934bcc43add6649/opwen_email_server/actions.py#L148) is incorrect?

**Comment by c-w** [comment]
@nzola Is this still a behavior you're seeing?

**Comment by c-w** [comment]
From @nzola:

> I have been testing Opwen-Webapp REV 0.5.11 all this week and this is the results:
> SENTBOXes of Lokole WEB and Lokole BOX do not mirror each other (they don't match).
> Outbound emails originated from the Lokole WEB are saved in Lokole WEB SENBOX only.
> Outbound emails originated from the Lokole BOX are saved in Lokole BOX SENTBOX only.

**Comment by nzola** [comment]
***** CORRESTION ******

The Lokole box "*SENTBOX*" show both, emails sent from *WEB* and emails
sent from the *BOX* . The Lokole *BOX* has no problems at all.
ONLY the *WEB SENTBOX* shows emails originated from it, but not emails sent
from the Lokole* BOX.*

Nzola

**Comment by c-w** [comment]
Resolving since this hasn't been reproduced in the latest releases.
