### ISSUE TITLE
ReplyAll button doesn't work

### ISSUE THREAD

**Issue by c-w** [ascoderu/lokole#449]
From @nzola:

> Reply to all button does not reply to all, but only to the sender. Same as simply reply button.

![Screenshot showing bug](https://user-images.githubusercontent.com/1086421/81600461-a3763800-9397-11ea-8e49-6c24368f9558.png)

Relevant section of the code: https://github.com/ascoderu/lokole/blob/4468eda976437da16b38cb81cad7408421402c40/opwen_email_client/webapp/forms/email.py#L165-L180

**Comment by sbathgate** [comment]
Took a quick look at this issue, I suspect the bug results from the inbox logic vs. the replyAll logic. If you include multiple emails in the To: field, i.e.
`to: shaun@developer1.lokole.ca, nzola@developer1.lokole.ca`
the receiving inbox appears to strip the additional addresses from the to field.

**Comment by c-w** [comment]
@nzola I have a fix for this which copies all the people on TO and CC from the email to the CC of the reply email when "reply all" is used. Hope that behavior works for you.
