### ISSUE TITLE
Enable email sync worker on IIAB

### ISSUE THREAD

**Issue by c-w** [ascoderu/lokole#454]
Currently the integration between Internet-in-a-Box (IIAB) and Lokole assumes a fully disconnected scenario which means that users of the system can only send emails between each other.

We had some requests from users whether it would be possible to extend the functionality to optionally enable email synchronization. This would require a few changes:

1) In the IIAB setup scripts, we currently run the gunicorn process for the Lokole email client (see [webapp.sh.j2](https://github.com/iiab/iiab/blob/930052c61995aa3d136bdb441d9d75397ea32434/roles/lokole/templates/webapp.sh.j2). We will have to extend this to also run the Lokole [email crontab](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/docker/client/run-crontab.sh), [celery worker](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/docker/client/run-celery.sh) and [restarter daemon](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/install.py#L700-L711).

2) The Lokole email client setup script (see [install.py](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/install.py#L793-L806)) currently registers a new Lokole client during while setting up the Lokole hardware device. I believe this may be difficult to integrate into the IIAB flow. To make our life easier, we could add an admin page to the Lokole client that enables calling the registration endpoint, storing the returned information in the configuration and then [restarting the application](https://github.com/ascoderu/lokole/blob/019611c3e40d6789c5359cbafd52a0c305d20bdb/opwen_email_client/webapp/actions.py#L94-L102) so that the new configuration gets picked up.

**Comment by c-w** [comment]
cc @holta as FYI and heads up of potential future pull requests

**Comment by c-w** [comment]
cc @aidan-fitz in case your team would be interested in working on this

**Comment by adamsclafani** [comment]
https://github.com/iiab/iiab/pull/2507

**Comment by holta** [comment]
> see iiab/iiab#2507

FYI iiab/iiab#2514 is the latest proposal.

@adamsclafani can you review that, and specify what you believe should be merged within the coming week ideally?

**Comment by adamsclafani** [comment]
Quick update on the task: [Part 1](https://github.com/iiab/iiab/pull/2514) which has been merged.

**Comment by adamsclafani** [comment]
For the client setup, I was thinking a simple form where someone specifies the client name then hits a register button linked to a new route (admin/register). Also would it be possible to re-use the Client Setup class in the install script or should we just add a new Client setup specifically for IIAB usage that also leverages the restarter within the same action? Thoughts?

**Comment by c-w** [comment]
@adamsclafani Yes, that works. Here's some more detail on what I suggest to be done:

- [ ] When the opwen_email_client starts, check if the one-time device setup has already been done. I think the simplest way to figure out if the setup needs to be run is to check if the `OPWEN_CLIENT_ID` setting ([code](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/opwen_email_client/webapp/config.py#L126)) is `None` and if the `OPWEN_SIM_TYPE` setting ([code](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/opwen_email_client/webapp/config.py#L101)) isn't set to `LocalOnly`. If the setup needs to be run, redirect to a special page that will guide the user through the setup. I believe the simplest way to achieve the check is to have a [before_first_request](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Flask.before_first_request) hook that calls to [redirect](https://flask.palletsprojects.com/en/1.1.x/api/#flask.redirect).

- [ ] For the setup page, create a new view similar to the admin settings page ([code](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/opwen_email_client/webapp/views.py#L266)) with an associated form ([code](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/opwen_email_client/webapp/forms/settings.py#L20)) and template ([code](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/opwen_email_client/webapp/templates/settings.html)). When the form is submitted, all the settings from the `install.py` script `ClientSetup` and `WebappSetup` steps (see [here](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/install.py#L541-L549) and [here](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/install.py#L456-L459)) should be written to the settings file at the path `OPWEN_SETTINGS`. I think the only piece of information we have to ask from the user is the `OPWEN_CLIENT_NAME` alongside their registration credentials (Github username and personal access token). We then take these three pieces of information and make the request to the cloud service to register the client ([code](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/install.py#L423-L453)), take the values from the registration response and write them to the settings file. Note that this step should also handle error responses from the registration call and display them to the user, e.g. in case the client name is already taken or the registration credentials aren't recognized.

- [ ] @adamsclafani I added your Github account to the registration group so you should be able to call the registration endpoint for testing if you create a personal access token with the `read:org` scope ([docs](https://docs.github.com/en/enterprise/2.15/user/articles/creating-a-personal-access-token-for-the-command-line)); I would just ask to delete your test clients when you no longer need them. You can manage your client registrations via the API ([spec](https://mailserver.lokole.ca/api/email/register/swagger.json)) or by logging into the management dashboard using your Github username and personal access token ([link](https://ascoderu.ca/lokole/)).

- [ ] After the setup form is submitted and all the values were written to the settings file, the webapp must be restarted. This can be achieved by calling the `RestartApp` command ([code](https://github.com/ascoderu/lokole/blob/dba2b88f3f03533dd4ff477efd95ece9c56c00b2/opwen_email_client/webapp/actions.py#L94-L102)).

I don't think the net new code that must be added is all that much (essentially a new page in the Flask app that makes a HTTP request and writes some values to a file) but there's a lot of existing code in the installer script to read, understand, and port, so don't hesitate to reach out if you have any questions, comments, or concerns!

**Comment by adamsclafani** [comment]
@c-w Ok awesome, thanks for the details, that helps a lot! I agree, although new net code isn't too much, there's definitely a lot going on here so I'll definitely throw questions your way!

**Comment by c-w** [comment]
@adamsclafani Is this complete? If so please close the task. Thanks!
