### ISSUE TITLE
Email services don't work from Lokole client

### ISSUE THREAD

**Issue by c-w** [ascoderu/lokole#458]
From @nzola 

> echo@bot.lokole.ca does not work with the BOX , but works ok with the WEB. All the emails sent to echo@bot.lokole.ca from the Lokole BOX replies end up in the WEB inbox and never reach the BOX inbox.

**Comment by c-w** [comment]
@adamsclafani Would you mind looking into this?

**Comment by adamsclafani** [comment]
hmmmmmmm, this one is a bit of a head scratcher. I'll look into it!

**Comment by adamsclafani** [comment]
I just tested the echo service with my team email and it seems to be working. I don't have a box so this is the closest thing I have to test with. Maybe @nzola could send an email from a box and @c-w pull the logs?

**Comment by nzola** [comment]
@c-w @adamsclafani I have been testing this issue again since yesterday. I have noticed the system is working but inconsistently. Sometimes the echo return emails to Lokole inbox, sometimes not.
I will keep testing and will report again on May 20, 2020.

**Comment by nzola** [comment]
@c-w @adamsclafani I have 2 clients; westest1 and westest2.
1- westest1 client email service is working fine. echo@bot replies are showing up in both inboxes; webmail and Lokole boxes.
2- westest2 client email service is working partially. echo@bot replies are showing up in webmail inbox only, but not in Lokole box inbox.
I have noticed sometimes the webmail inbox get double replies of one message sent to echoe@bot. May be the reply which is supposed to reach Lokole box is doubled in the webmail inbox??
-

**Comment by adamsclafani** [comment]
@nzola Funny enough, after checking my webmail account again, I noticed I got a double reply from the echo service as well

**Comment by adamsclafani** [comment]
@nzola @c-w I've never experienced any weird behavior from the service when utilizing my gmail account. I think the issue lies somewhere in the actual email delivery. Maybe this is related to #459?

**Comment by adamsclafani** [comment]
@nzola @c-w I utilized my webmail to send an email to myself and I also get double repeating emails.

**Comment by nzola** [comment]
@adamsclafani @c-w @sbathgate Yes Adam, I agree. It is the same issue as #459 I have included Shaun B. in this conversation as he had worked on this situation before. It is not just echo@bot replies to westest2 not working, but also any emails from Internet sent to westest2 is not reaching the inbox of the Lokole box. The webmail of westest2 is working perfectly. Also the sentbox of Lokole box syncs with webmail sentbox without any problems.

**Comment by sbathgate** [comment]
I'll take a look into this tomorrow, and let you know what I come up with.

**Comment by nzola** [comment]
Thanks Shaun!

**Comment by sbathgate** [comment]
I have managed to replicate the duplicate emails on my shaun@team.lokole.ca. There is roughly a 30 second delay between the duplicates coming through. I will take a peek at some of the recent changes and see if one is potentially pulling the email twice. 

@nzola Your westest2 email was not setup in cloudflare. I have manually added it to it, this should resolve some of your issues.

**Comment by sbathgate** [comment]
I am going to close this issue and open a new one for the duplicate inbox messages. The original fault stemmed from westest2 not having a dns configured.
