### ISSUE TITLE
Python package name change

### ISSUE THREAD

**Issue by jvonau** [ascoderu/lokole#538]
https://github.com/ascoderu/lokole/blob/1c189e0f9ec689fce98e8b7c47152678bcf00aca/install.py#L484
https://github.com/iiab/iiab/commit/80c75fd6f80f704e09944947101c50c68a699669
>root@box:/# apt list bcrypt
Listing... Done
root@box:/# apt list python3-bcrypt
Listing... Done
python3-bcrypt/hirsute,now 3.1.7-4 arm64 [installed]

python3-bcrypt

**Comment by holta** [comment]
@adamsclafani ran into a related bug overnight.

Can someone make a recommendation or PR here?

Thanks!

cc: deldesir
