### ISSUE TITLE
Lokole fails to install with Python 3.9+ [Lokole requirements.txt file needs updating]

### ISSUE THREAD

**Issue by holta** [ascoderu/lokole#585]
Any Python developers who can assist, please see:

- iiab/iiab#3132

Thank you!

**Comment by jvonau** [comment]
https://itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/

**Comment by holta** [comment]
Should this issue be kept open or closed?

FYI this Internet-in-a-Box PR is now merged:

- PR iiab/iiab#3149

**Comment by nzola** [comment]
Is this problem fixed? The Lokole can now install on IIAB now?
I have found a freelancer who wants to talk to me today to negotiate about working on this error.
@jvonau What can you tell me? By the way, I am running iiab full install now with  Raspios64bits and started 15 minutes ago.

**Comment by jvonau** [comment]
Not fixed here, just have a workaround in place within IIAB.

**Comment by nzola** [comment]
@jvonau thanks for the clarifications. Should I put you in contact with whoever I would find to help correct the problem?
By the way, iiba full big install has just completed without problems. I have published the iiab-diagnostics of my install.

**Comment by jvonau** [comment]
Just point out the above link to the fix in IIAB, your recruit should know what to do, or find somebody else. Other Ref: https://stackoverflow.com/questions/71618764/why-flask-cli-suddenly-throws-import-error-when-3-commit-before-worked-fine-no

**Comment by nzola** [comment]
Thanks @jvonau

**Comment by holta** [comment]
Thanks again to @jvonau who provided this interim patch/workaround below ([within IIAB](https://github.com/iiab/iiab/pull/3149/files)) until Lokole fixes its own [requirements.txt](https://github.com/ascoderu/lokole/blob/master/requirements.txt) !

- PR iiab/iiab#3149

**Comment by holta** [comment]
@nzola I hope this is resolved quickly in coming days!

In any case. I've posted a 2-sentence public advisory to help newcomers &mdash; summarizing the situation in the "Known Issues" section at the bottom here:

- https://github.com/iiab/iiab/wiki/IIAB-8.0-Release-Notes#known-issues

**Comment by holta** [comment]
@mabuelhagag and @nzola can this ticket be closed now?

Context: About a year ago I was told that Lokole needed to update its own requirements.txt file, as this was obliging IIAB implementers to install Lokole twice as a temporary workaround &mdash; as detailed at https://github.com/iiab/iiab/issues/2833#issuecomment-931559600 and mentioned on PR iiab/iiab#3149.

Thanks for clarifying!

**Comment by nzola** [comment]
> 

To my side, I confirm the Lokole thru IIAB install is smooth and I am satisfied. I recommand this issue be closed, unless otherwise.
Thanks

**Comment by mabuelhagag** [comment]
I'm closing this now. Thank you everyone for all your help and support ❤️
